### ISSUE TITLE
skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒

### ISSUE THREAD

**Issue by ghost** [caistly/labilityrip#1]
skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒skid🐒

**Comment by caistly** [comment]
"skid" bud you couldn't even fix a skidded site. u are the dumbest mf of all time :trollface:
